var cText = ''
        cText+='<p><a href="intro.html">Introduction</a></p>'
        cText+='<p><a href="http://groups.google.com/group/mobicents-public">Forum</a></p>'
        cText+='<p><a href="http://mobicents.googlecode.com/svn/trunk/">Anonymous SVN</a></p>'
        cText+='<p><a href="https://mobicents.googlecode.com/svn/trunk/">Committer SVN</a></p>'
        cText+='<p><a href="http://code.google.com/p/mobicents/source/browse/trunk/protocols/ss7/isup">Browse SVN</a></p>'
        cText+='<p><a href="http://groups.google.com/group/mobicents-public/web">User Wiki</a></p>'
        cText+='<p><a href="docs.html">Documentation</a></p>'
        cText+='<p><a href="http://code.google.com/p/mobicents/issues/list?can=2&q=Component-ISUP&colspec=ID+Priority+Component+Milestone+Version+Release+Type+Status+Owner+Summary&cells=tiles">Issue Tracker</a></p>'
        cText+='<p><a href="roadmap.html">Roadmap</a></p>'
document.write(cText)